# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: doc-ci
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "cmds/**"
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "cmds/**"
      - "**.md"
  workflow_dispatch:
jobs:
  cli-test:
    runs-on: doc
    timeout-minutes: 40
    strategy:
      fail-fast: true

    steps:
    - name: config-net
      run: |
        export http_proxy=http://bigdata_open_proxy:H89k5qwQRDYfz@10.140.90.20:10811
        export https_proxy=http://bigdata_open_proxy:H89k5qwQRDYfz@10.140.90.20:10811
    - name: doc cli
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
      
    - name: check-requirements
      run: |
        changed_files=$(git diff --name-only -r HEAD~1 HEAD)
        echo $changed_files
        if [[ $changed_files =~ "requirements.txt" ]]; then
          pip install -r requirements.txt
        fi

    - name: config-net-reset
      run: |
        export http_proxy=""
        export https_proxy=""
    - name: test_cli
      run: |
        echo $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE && export PYTHONPATH=. && pytest -s -v tests/test_unit.py
        cd $GITHUB_WORKSPACE &&  pytest -s -v test/test_cli/test_cli.py
                                                                                                                            
